# ===================================================================
# Copyright © 2025 Sackey Ezekiel Etrue
# Distributed under the terms of the MIT license.
# ===================================================================

load("@rules_cc//cc:cc_library.bzl", "cc_library")
#===========================
# Build C++ Library        #
#===========================

cc_library(
	name = "myyaml",
	srcs = [
		"src/myyaml.cpp",
	],
	hdrs = glob(["include/myyaml/*.h", "include/myyaml/*.hpp"]),
    linkstatic = True,
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
)

#===========================
# Build C Library          #
#===========================

cc_library(
	name = "myyamlc",
	srcs = [
		"src/myyamlc.cpp",
	],
	hdrs = glob(["include/myyaml/*.h", "include/myyaml/*.hpp"]),
    linkstatic = True,
	visibility = ["//visibility:public"],
	includes = ["include"],
	copts = ["-std=c++17"],
	deps = [":myyaml"],
)

# ===================================================================
